---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
  namespace: prod
  labels:
    app: nginx
spec:
  replicas: 1
  namespace: prod
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      namespace: prod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: bujarbakiu/nginx:v0.1.0
          ports: 
            - containerPort: 80
      
