---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-private
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:bbakiu/learning-argocd-private.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----

    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"